version: 2
updates:
  - package-ecosystem: "npm" # Use "pip" for Python, "maven" for Java, etc.
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
